# Generated by Django 3.2.5 on 2022-09-12 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guia', '0001_initial'),
        ('argumento', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id_agenda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='agenda', serialize=False, to='guia.guia')),
            ],
        ),
        migrations.CreateModel(
            name='Cubrimiento',
            fields=[
                ('id_cubrimiento', models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('oficina', models.CharField(max_length=80)),
                ('direccion', models.CharField(max_length=100)),
                ('dias', models.CharField(max_length=6)),
                ('direccion_cita', models.CharField(max_length=180)),
                ('postal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('orden', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now=True, null=True)),
                ('nombre_orden', models.CharField(max_length=25)),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Postal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='datos_g',
            fields=[
                ('seudo_dg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='guia_d_g', serialize=False, to='guia.guia')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha fisico')),
                ('d_i', models.BigIntegerField(blank=True, null=True, verbose_name='Documento de identidad')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('dest', models.CharField(blank=True, max_length=100, null=True, verbose_name='Destinatario')),
                ('d_i_a', models.CharField(blank=True, max_length=12, null=True, verbose_name='CC autorizado')),
                ('autor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Autorizado')),
                ('barrio', models.CharField(blank=True, max_length=70, null=True)),
                ('marca', models.CharField(blank=True, max_length=15, null=True)),
                ('gx', models.BigIntegerField(blank=True, null=True)),
                ('gy', models.BigIntegerField(blank=True, null=True)),
                ('zona', models.CharField(blank=True, max_length=30, null=True)),
                ('cantidad', models.IntegerField()),
                ('cod_vis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='argumento.cod_vis')),
                ('id_ciu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.ciudad', verbose_name='Id ciudad')),
                ('id_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='argumento.estado', verbose_name='Estado')),
                ('id_pro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='argumento.producto', verbose_name='Producto')),
                ('mot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='argumento.motivo', verbose_name='motivo')),
                ('oficina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.oficinas')),
                ('orimp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orden_datos_g', related_query_name='orden_dat_g', to='datos_g.orden', verbose_name='Orden impresion')),
                ('postal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_g.postal')),
                ('proc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='argumento.proceso', verbose_name='Proceso')),
            ],
            options={
                'verbose_name': 'Datos de gestion',
                'verbose_name_plural': 'Datos de gestion',
            },
        ),
    ]
