# Generated by Django 3.2.5 on 2022-09-12 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datos_g', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_g',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario_datog'),
        ),
        migrations.AddField(
            model_name='cubrimiento',
            name='dane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ciudad', to='cliente.ciudad'),
        ),
    ]
