# Generated by Django 3.2.5 on 2022-12-21 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('argumento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bd_clie',
            fields=[
                ('seudo_bd', models.CharField(max_length=35, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=180)),
                ('cc', models.CharField(max_length=12)),
                ('archivo', models.CharField(blank=True, max_length=15, null=True)),
                ('jornada', models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], max_length=3, null=True)),
                ('canal', models.CharField(blank=True, max_length=8, null=True)),
                ('realz', models.CharField(blank=True, max_length=30, null=True, verbose_name='Realzador')),
                ('tipo', models.CharField(blank=True, max_length=30, null=True)),
                ('tarjeta', models.CharField(blank=True, max_length=30, null=True)),
                ('referencia', models.CharField(blank=True, max_length=50, null=True)),
                ('convenio', models.CharField(blank=True, max_length=50, null=True)),
                ('id_serv', models.IntegerField(verbose_name='Id Servicio')),
                ('fecha', models.DateField()),
                ('sucursal', models.CharField(blank=True, max_length=50, null=True)),
                ('fisicos', models.CharField(choices=[('1', 'Fisico'), ('2', 'No llego fisico'), ('3', 'Fisico paquete')], max_length=8)),
                ('telefono', models.CharField(blank=True, max_length=80, null=True)),
                ('franquicia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='argumento.franquicia')),
                ('id_clie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente', verbose_name='Id cliente')),
                ('id_est_clie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='argumento.est_clie', verbose_name='Id estado cliente ')),
                ('nom_pro', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='argumento.nom_producto', verbose_name='Nombre del producto')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='argumento.producto')),
                ('t_emi', models.ForeignKey(max_length=4, on_delete=django.db.models.deletion.CASCADE, to='argumento.emision', verbose_name='Tipo Emision')),
            ],
            options={
                'verbose_name': 'Base Cliente',
                'verbose_name_plural': 'Base Cliente',
            },
        ),
        migrations.CreateModel(
            name='Agenda_bd',
            fields=[
                ('id_agenda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='agenda', serialize=False, to='base_cliente.bd_clie')),
            ],
        ),
        migrations.CreateModel(
            name='No_fisico',
            fields=[
                ('seudo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base_cliente.bd_clie')),
            ],
        ),
    ]
