# Generated by Django 3.2.5 on 2022-12-21 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('argumento', '0001_initial'),
        ('guia', '0001_initial'),
        ('fisico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rastreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivopr', models.CharField(blank=True, max_length=30, null=True)),
                ('mensajero', models.CharField(max_length=120)),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('guia_tracking', models.IntegerField(blank=True, null=True)),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='argumento.estado')),
                ('id_fisico_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fisco_tracking', to='fisico.fisico')),
                ('id_guia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trackin_guia', to='guia.guia')),
            ],
        ),
    ]
