# Generated by Django 3.2.5 on 2023-03-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_rastreo_seudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rastreo',
            name='ciudad',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
