# Generated by Django 3.2.5 on 2023-03-16 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_rastreo_ciudad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rastreo',
            options={'ordering': ['id']},
        ),
    ]
