# Generated by Django 3.2.5 on 2023-03-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_alter_rastreo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rastreo',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
