# Generated by Django 3.2.5 on 2023-03-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_alter_rastreo_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='rastreo',
            name='estado_final',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
