# Generated by Django 3.2.5 on 2023-04-01 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_cliente_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='Servicio',
        ),
    ]
