# Generated by Django 3.2.5 on 2023-04-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_cliente_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rol',
            field=models.CharField(blank=True, choices=[('1', 'Administracion'), ('2', 'Asesor')], max_length=2, null=True),
        ),
    ]
