# Generated by Django 3.2.5 on 2023-06-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_auto_20230608_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(max_length=30)),
            ],
        ),
    ]
