# Generated by Django 3.2.5 on 2023-06-28 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_zona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zona',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.ciudad'),
        ),
    ]
