# Generated by Django 3.2.5 on 2023-06-28 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0011_alter_zona_zona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_barrio', models.CharField(max_length=30)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.zona')),
            ],
        ),
    ]
