# Generated by Django 3.2.5 on 2022-12-21 22:29

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fisico', '0001_initial'),
        ('base_cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoberturaPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdf_cobertura')),
                ('fecha', models.DateTimeField(auto_now=True, null=True, verbose_name='fecha cobertura')),
            ],
        ),
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('fisico_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='fisico.fisico')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('seudo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='guias', serialize=False, to='base_cliente.bd_clie')),
                ('postal', models.CharField(blank=True, max_length=7, null=True)),
                ('barrio', models.CharField(blank=True, max_length=70, null=True)),
                ('contiene', models.CharField(blank=True, max_length=50, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('domicilio', models.IntegerField(blank=True, default=0, null=True)),
                ('declarado', models.IntegerField(blank=True, default=0, null=True)),
                ('tel', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'verbose_name': 'Buscar',
                'verbose_name_plural': 'Guia',
            },
            bases=('fisico.fisico', models.Model),
        ),
        migrations.CreateModel(
            name='Guiap',
            fields=[
                ('seudof', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=70)),
                ('edad', models.IntegerField()),
                ('telefono', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('domicilio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalGuia',
            fields=[
                ('fisico_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='fisico.fisico')),
                ('bolsa_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='fisico.bolsa')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('fecha', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha fisico')),
                ('estado', models.BooleanField(default=True)),
                ('bolsa', models.CharField(db_index=True, max_length=11, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('codigo', models.CharField(blank=True, max_length=28, null=True)),
                ('fecha_bolsa', models.DateTimeField(blank=True, editable=False, null=True)),
                ('cantidad_vi', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad visitas')),
                ('fecha_visita', models.DateTimeField(blank=True, null=True)),
                ('fecha_recepcion', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha gestion')),
                ('id_guia', models.IntegerField(blank=True, db_index=True)),
                ('direccion', models.CharField(blank=True, max_length=240, null=True)),
                ('cantidad', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Cantidad Total')),
                ('destinatario', models.CharField(blank=True, max_length=100, null=True)),
                ('d_i', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_planilla', models.DateTimeField(blank=True, null=True)),
                ('est_planilla', models.CharField(blank=True, max_length=30, null=True)),
                ('id_planilla', models.IntegerField(blank=True, null=True)),
                ('fecha_descargue', models.DateField(blank=True, null=True, verbose_name='Descargue')),
                ('origen', models.CharField(blank=True, max_length=60, null=True)),
                ('destino', models.CharField(blank=True, max_length=60, null=True)),
                ('estado_destino', models.BooleanField(default=False)),
                ('postal', models.CharField(blank=True, max_length=7, null=True)),
                ('barrio', models.CharField(blank=True, max_length=70, null=True)),
                ('contiene', models.CharField(blank=True, max_length=50, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('domicilio', models.IntegerField(blank=True, default=0, null=True)),
                ('declarado', models.IntegerField(blank=True, default=0, null=True)),
                ('tel', models.CharField(blank=True, max_length=80, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Buscar',
                'verbose_name_plural': 'historical Guia',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_serv', models.IntegerField(primary_key=True, serialize=False)),
                ('Servicio', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicio',
            },
        ),
        migrations.CreateModel(
            name='img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='guia')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('mod_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('estado_img', models.CharField(blank=True, choices=[('ENTREGA_DIGITALIZADA', 'ENTREGA DIGITALIZADA')], default='ENTREGA_DIGITALIZADA', max_length=22, null=True, verbose_name='gestion')),
                ('id_guia', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_mesa', to='fisico.fisico')),
            ],
            options={
                'verbose_name': 'Imagenes Guia',
                'verbose_name_plural': 'Imagenes Guia',
            },
        ),
    ]
