# Generated by Django 3.2.5 on 2023-03-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0004_historicalguia_img_guia_courrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalguia',
            name='img_fachada_courrier',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
