# Generated by Django 3.2.5 on 2023-03-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0005_historicalguia_img_fachada_courrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalguia',
            name='seudo_track',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
