# Generated by Django 3.2.5 on 2023-04-18 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courrier',
            name='id_veh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courrier.vehiculo', verbose_name='Datos vehiculo'),
        ),
    ]
