# Generated by Django 3.2.5 on 2023-02-23 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AcudeOtro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OtroTipoEstablecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OtroTipoSenalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Red',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEstablecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoNoEfectiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSenalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Daviplata',
            fields=[
                ('fecha_cargue', models.DateField(auto_now_add=True)),
                ('id_ruta', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_total', models.IntegerField()),
                ('nombre_establecimiento', models.CharField(max_length=200)),
                ('codigo_dian', models.IntegerField()),
                ('direccion_base', models.CharField(max_length=400)),
                ('rdab', models.CharField(max_length=100, verbose_name='REFERENCIAS DETALLES ADICIONALES BASE')),
                ('direccion_c_b', models.CharField(max_length=400, verbose_name='DIRECCIÓN COMPLETA BASE')),
                ('fecha_encuesta', models.DateField()),
                ('visita_efectiva', models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=2)),
                ('otro_especificado', models.CharField(blank=True, max_length=50, null=True)),
                ('pdv', models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=50, verbose_name='¿PDV permite realizar la visita?')),
                ('obervacion', models.TextField(max_length=300)),
                ('direccion_actualizada', models.CharField(max_length=400, verbose_name='Dirección Actualizada')),
                ('detalle_direccion', models.CharField(max_length=200, verbose_name='Detalle Dir actualizada')),
                ('direccion_completo', models.CharField(max_length=200, verbose_name='Completo actualizada')),
                ('coincide_direccion', models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=2)),
                ('mobre_e_a', models.CharField(max_length=200, verbose_name='Nombre del establecimiento actualizado')),
                ('nombre_coincide', models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=2)),
                ('nombre_atiende', models.CharField(max_length=150, verbose_name='Nombre de quien atendió la visita')),
                ('es_dueño', models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=2)),
                ('numero_movil', models.IntegerField()),
                ('establecimiento_cambio', models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=2, verbose_name='El establecimiento cambió de dueño en el ultimo año?')),
                ('se_implementa', models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=50, verbose_name='Se logro Implementar el Rompetráfico')),
                ('razon_no', models.CharField(max_length=150, verbose_name='Razón indicada de no implementacion')),
                ('impresora', models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=50, verbose_name='Herramientas: Impresora')),
                ('datafono', models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=50, verbose_name='Herramientas: Datafono')),
                ('lector', models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=50, verbose_name='Herramientas: Lector de código de barras')),
                ('computador', models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=50, verbose_name='Herramientas: Computador')),
                ('pago_propios', models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=50, verbose_name='Servicio: Pago de productos propios')),
                ('deposito_retiro_propio', models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=50, verbose_name='Servicio: Depósito de retiro DaviPlata')),
                ('servicio_pagos', models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=50, verbose_name='Servicio: Pagos de subsidios por giros')),
                ('servicio_recaudo', models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=50, verbose_name='Servicio: Recaudo servicios públicos y privados')),
                ('servicio_depositos', models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=50, verbose_name='Servicio: Depósitos y retiros de cuentas ahorro y corriente')),
                ('transacciones', models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=50, verbose_name='Conocimiento para realizar transacciones')),
                ('deposito_retiro', models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=50, verbose_name='Depósito y Retiro DAVIVIENDA')),
                ('pago_subsidios', models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=50, verbose_name='Pagos de Subsidios por Giro')),
                ('tip_seguridad', models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=50, verbose_name='Tips de Seguridad')),
                ('Sarlaft_activos', models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=50, verbose_name='Sarlaft/Lavado de activos')),
                ('recaudo_servicios', models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=50, verbose_name='Recaudo servicios públicos y privados')),
                ('tip_riesgo', models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=50, verbose_name='Tips de Riesgo')),
                ('fecha_capacitacion', models.DateField(verbose_name='Fecha de la última capacitación')),
                ('medio_especificado', models.CharField(max_length=30, verbose_name='Medio especificado')),
                ('material', models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=50)),
                ('ninguno_especificado', models.CharField(max_length=30)),
                ('url_img_f', models.ImageField(upload_to='IMG FACHADA', verbose_name='URL IMAGEN FACHADA')),
                ('url_img_m', models.ImageField(upload_to='IMG MATERIAL', verbose_name='URL IMAGEN IMPL. MATERIAL')),
                ('url_img_o', models.ImageField(upload_to='IMG OTRA', verbose_name='URL IMAGEN OTRA')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('visualizar', models.CharField(max_length=250)),
                ('grupo_etnico', models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=50, verbose_name='HACE PARTE DE UN GRUPO ETNICO')),
                ('cual', models.CharField(max_length=80, verbose_name='especificado Grupo Etnico')),
                ('acude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daviplata.acude', verbose_name='¿A quien acude?')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.departamento')),
                ('medio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daviplata.medio')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.ciudad')),
                ('otro_d_e', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daviplata.otrotipoestablecimiento', verbose_name='Otro tipo de establecimiento')),
                ('otro_senalizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daviplata.otrotiposenalizacion', verbose_name='Otro especificado')),
                ('red', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daviplata.red')),
                ('sarlaft_informa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daviplata.acudeotro', verbose_name='SARLAFT. ¿A quien informaría?')),
                ('t_senalizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daviplata.tiposenalizacion', verbose_name='Tipo de señalizacion')),
                ('tipo_establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daviplata.tipoestablecimiento')),
                ('tipo_no_efectiva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daviplata.tiponoefectiva')),
            ],
        ),
    ]
