# Generated by Django 3.2.5 on 2023-04-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculacion',
            name='no_register',
            field=models.CharField(blank=True, choices=[('Cliente ya estaba registrado', 'Cliente ya estaba registrado'), ('Fallas en la app', 'Fallas en la app'), ('Cliente no esta interesado', 'Cliente no esta interesado'), ('Cliente tercera edad', 'Cliente tercera edad'), ('Sistema operativo no permite registro', 'Sistema operativo no permite registro'), ('Cliente desconfia', 'Cliente desconfia'), ('Cliente no tiene tiempo', 'Cliente no tiene tiempo'), ('Cliente no tiene documentos en el momento', 'Cliente no tiene documentos en el momento'), ('Modo contingencia', 'Modo contingencia')], max_length=60, null=True, verbose_name='¿Por que no se realizo el registro en perfil mi negocio?'),
        ),
    ]
