# Generated by Django 3.2.5 on 2023-02-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0002_auto_20230227_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daviplata',
            name='url_img_f',
            field=models.ImageField(blank=True, null=True, upload_to='IMG FACHADA', verbose_name='URL IMAGEN FACHADA'),
        ),
        migrations.AlterField(
            model_name='daviplata',
            name='url_img_m',
            field=models.ImageField(blank=True, null=True, upload_to='IMG MATERIAL', verbose_name='URL IMAGEN IMPL. MATERIAL'),
        ),
        migrations.AlterField(
            model_name='daviplata',
            name='url_img_o',
            field=models.ImageField(blank=True, null=True, upload_to='IMG OTRA', verbose_name='URL IMAGEN OTRA'),
        ),
    ]
