# Generated by Django 3.2.5 on 2023-04-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0003_alter_vinculacion_se_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculacion',
            name='contingencia',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2, null=True, verbose_name='¿Cliente contingencia?'),
        ),
    ]
