# Generated by Django 3.2.5 on 2023-02-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0004_auto_20230228_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daviplata',
            name='codigo_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
