# Generated by Django 3.2.5 on 2023-03-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0005_alter_daviplata_codigo_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daviplata',
            name='latitud',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='daviplata',
            name='longitud',
            field=models.CharField(max_length=15),
        ),
    ]
