# Generated by Django 3.2.5 on 2023-04-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0005_alter_vinculacion_razon_no_sticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculacion',
            name='transaccion',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True),
        ),
    ]
