# Generated by Django 3.2.5 on 2023-04-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0006_vinculacion_transaccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculacion',
            name='codigo_transaccion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
