# Generated by Django 3.2.5 on 2023-03-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0006_auto_20230323_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vinculacion',
            fields=[
                ('tipo_id', models.CharField(choices=[('CC', 'CC'), ('NIT', 'NIT'), ('CC DE EXTRANJERIA', 'CC DE EXTRANJERIA')], max_length=50, verbose_name='Tipo de identificación')),
                ('identificacion', models.CharField(max_length=13, primary_key=True, serialize=False)),
            ],
        ),
    ]
