# Generated by Django 3.2.5 on 2023-04-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0007_vinculacion_codigo_transaccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculacion',
            name='no_transaccion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
