# Generated by Django 3.2.5 on 2023-03-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0008_vinculacion_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculacion',
            name='nombre',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
