# Generated by Django 3.2.5 on 2023-04-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0009_auto_20230412_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculacion',
            name='sig_factura',
            field=models.CharField(blank=True, choices=[('Vinculacion Estandar', 'Vinculacion Estandar'), ('Vinculacion Sin activacion Perfil', 'Vinculacion Sin activacion Perfil'), ('Remarcacion', 'Remarcacion'), ('Comercio No acepto', 'Comercio No acepto')], max_length=45, null=True),
        ),
    ]
