# Generated by Django 3.2.5 on 2023-04-17 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0010_vinculacion_sig_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculacion',
            name='tipo_gestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daviplata.tipogestion'),
        ),
    ]
