# Generated by Django 3.2.5 on 2023-03-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0011_alter_vinculacion_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculacion',
            name='nombre_comercio',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
