# Generated by Django 3.2.5 on 2023-04-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0011_alter_vinculacion_tipo_gestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipogestion',
            name='descripcion',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
