# Generated by Django 3.2.5 on 2023-04-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0012_tipogestion_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculacion',
            name='registro_daviplata',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO'), ('Ya esta activo', 'Ya esta activo'), ('Modo Contingencia', 'Modo Contingencia')], max_length=20, null=True, verbose_name='¿Se realizó registro en DaviPlata?'),
        ),
    ]
