# Generated by Django 3.2.5 on 2023-03-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0013_vinculacion_fecha_visita'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComercioVinculacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('c_rut', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, verbose_name='¿Comercio cuenta con RUT?')),
            ],
        ),
        migrations.RemoveField(
            model_name='vinculacion',
            name='nombre_comercio',
        ),
    ]
