# Generated by Django 3.2.5 on 2023-03-29 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0014_auto_20230329_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comerciovinculacion',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='daviplata.vinculacion'),
        ),
    ]
