# Generated by Django 3.2.5 on 2023-04-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0015_alter_vinculacion_solicito_tencard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculacion',
            name='sticker',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='Se pego Sticker'),
        ),
    ]
