# Generated by Django 3.2.5 on 2023-03-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0018_vinculacion_tipo_gestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculacion',
            name='celular',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
