# Generated by Django 3.2.5 on 2023-03-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0019_vinculacion_celular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
    ]
