# Generated by Django 3.2.5 on 2023-03-29 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0020_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculacion',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='daviplata.categorias'),
            preserve_default=False,
        ),
    ]
