# Generated by Django 3.2.5 on 2023-04-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0020_alter_vinculacion_fecha_visita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculacion',
            name='fecha_visita',
            field=models.DateField(null=True),
        ),
    ]
