# Generated by Django 3.2.5 on 2023-03-29 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('daviplata', '0021_vinculacion_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculacion',
            name='dane',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cliente.ciudad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vinculacion',
            name='direccion',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vinculacion',
            name='latitud',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vinculacion',
            name='longitud',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
