# Generated by Django 3.2.5 on 2023-04-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0022_alter_vinculacion_fecha_visita'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculacion',
            name='fecha_registro',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
