# Generated by Django 3.2.5 on 2023-03-30 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0023_auto_20230330_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculacion',
            name='motivo_no_registro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='daviplata.motivonoregistro', verbose_name='¿Por qué no se realizó el registro DaviPlata?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vinculacion',
            name='no_registro',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default=1, max_length=2, verbose_name='¿Por qué no se realizó el registro en perfil mi negocio?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vinculacion',
            name='se_registro',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default=1, max_length=2, verbose_name='¿Se realizó registro en perfil mi negocio?'),
            preserve_default=False,
        ),
    ]
