# Generated by Django 3.2.5 on 2023-04-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0024_alter_vinculacion_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculacion',
            name='no_register',
            field=models.CharField(blank=True, choices=[('Cliente ya estaba registrado', 'Cliente ya estaba registrado'), ('Fallas en la app', 'Fallas en la app'), ('Cliente no esta interesado', 'Cliente no esta interesado'), ('Cliente tercera edad', 'Cliente tercera edad'), ('Sistema operativo no permite registro', 'Sistema operativo no permite registro'), ('Cliente desconfia', 'Cliente desconfia'), ('Cliente no tiene tiempo', 'Cliente no tiene tiempo'), ('Cliente no tiene documentos en el momento', 'Cliente no tiene documentos en el momento')], max_length=60, null=True, verbose_name='¿Por que no se realizo el registro en perfil mi negocio?'),
        ),
        migrations.AlterField(
            model_name='vinculacion',
            name='porque_no_solicito',
            field=models.CharField(blank=True, choices=[('Clinete ya tiene la tencard', 'Clinete ya tiene la tencard'), ('Fallas en la app', 'Fallas en la app'), ('No permitió el registro en el perfil mi negocio', 'No permitió el registro en el perfil mi negocio'), ('Cliente no esta interesado', 'Cliente no esta interesado'), ('Solo activo Daviplata para subsidios del gobierno', 'Solo activo Daviplata para subsidios del gobierno')], max_length=80, null=True, verbose_name='¿Por qué no se solicitó la tentcard?'),
        ),
        migrations.AlterField(
            model_name='vinculacion',
            name='registro_daviplata',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO'), ('Ya esta activo', 'Ya esta activo')], max_length=20, null=True, verbose_name='¿Se realizó registro en DaviPlata?'),
        ),
        migrations.AlterField(
            model_name='vinculacion',
            name='se_registro',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO'), ('Ya esta activo', 'Ya está activo')], max_length=20, null=True, verbose_name='¿Se realizó registro en perfil mi negocio?'),
        ),
        migrations.AlterField(
            model_name='vinculacion',
            name='solicito_tencard',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO'), ('Ya tiene la tencard', 'Ya tiene la tencard')], max_length=40, null=True, verbose_name='¿Se solicitó la tentcard?'),
        ),
    ]
