# Generated by Django 3.2.5 on 2023-03-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0024_auto_20230330_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculacion',
            name='solicito_tencard',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default=11, max_length=2, verbose_name='¿Se solicitó la tentcard?'),
            preserve_default=False,
        ),
    ]
