# Generated by Django 3.2.5 on 2023-03-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0025_vinculacion_solicito_tencard'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculacion',
            name='flanger',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default=1, max_length=2, verbose_name='Se instaló Flanger'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vinculacion',
            name='sticker',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default=1, max_length=2, verbose_name='Se pego Sticker'),
            preserve_default=False,
        ),
    ]
