# Generated by Django 3.2.5 on 2023-04-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0025_auto_20230427_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculacion',
            name='novedad',
            field=models.BooleanField(default=True),
        ),
    ]
