# Generated by Django 3.2.5 on 2023-04-27 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0026_vinculacion_novedad'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovedadVinculacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_vinculacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daviplata.vinculacion')),
            ],
        ),
    ]
