# Generated by Django 3.2.5 on 2023-03-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0027_vinculacion_porque_no_solicito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculacion',
            name='porque_no_solicito',
            field=models.CharField(choices=[('No esta interesado', 'No esta interesado'), ('NO le llama la atención', 'NO le llama la atención '), ('Solo trabaja con Nequi', 'Solo trabaja con Nequi '), ('Le parece Complicado Manejarlo', 'Le parece Complicado Manejarlo')], max_length=60, verbose_name='¿Por qué no se solicitó la tentcard?'),
        ),
    ]
