# Generated by Django 3.2.5 on 2023-04-28 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_alter_cliente_rol'),
        ('daviplata', '0027_novedadvinculacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculacion',
            name='dane',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.ciudad'),
        ),
    ]
