# Generated by Django 3.2.5 on 2023-03-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0028_alter_vinculacion_porque_no_solicito'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculacion',
            name='razon_no_flanger',
            field=models.CharField(choices=[('No esta interesado', 'No esta interesado'), ('NO le llama la atención', 'NO le llama la atención '), ('Solo trabaja con Nequi', 'Solo trabaja con Nequi '), ('Le parece Complicado Manejarlo', 'Le parece Complicado Manejarlo')], default=1, max_length=60, verbose_name='Razón por la cual no se instaló el flanger'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vinculacion',
            name='razon_no_sticker',
            field=models.CharField(choices=[('No esta interesado', 'No esta interesado'), ('NO le llama la atención', 'NO le llama la atención '), ('Solo trabaja con Nequi', 'Solo trabaja con Nequi '), ('Le parece Complicado Manejarlo', 'Le parece Complicado Manejarlo')], default=1, max_length=60, verbose_name='Razón por la cual no se pegó el sticker'),
            preserve_default=False,
        ),
    ]
