# Generated by Django 3.2.5 on 2023-03-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0029_auto_20230330_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoActivacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
    ]
