# Generated by Django 3.2.5 on 2023-04-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0030_alter_gestores_fecha_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestores',
            name='fecha_retiro',
            field=models.DateField(null=True, verbose_name='Fecha de Retiro del asesor'),
        ),
        migrations.AlterField(
            model_name='gestores',
            name='fecha_contrato',
            field=models.DateField(),
        ),
    ]
