# Generated by Django 3.2.5 on 2023-03-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0031_vinculacion_tipo_activacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculacion',
            name='datafono',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default=1, max_length=2, verbose_name='¿Comercio tiene Datafono?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vinculacion',
            name='interesado',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default=1, max_length=2, verbose_name='¿Comercio está interesado en ser corresponsal?'),
            preserve_default=False,
        ),
    ]
