# Generated by Django 3.2.5 on 2023-05-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0032_alter_gestores_fecha_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestores',
            name='fecha_contrato',
            field=models.DateField(blank=True, null=True),
        ),
    ]
