# Generated by Django 3.2.5 on 2023-04-03 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0032_auto_20230330_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculacion',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daviplata.categorias', verbose_name='¿A cual de las siguientes categorias pertenece el comercio?'),
        ),
    ]
