# Generated by Django 3.2.5 on 2023-05-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0033_alter_gestores_fecha_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestores',
            name='barrio',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
