# Generated by Django 3.2.5 on 2023-04-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0034_alter_vinculacion_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculacion',
            name='datafono',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, verbose_name='¿Comercio está interesado en Datafóno?'),
        ),
    ]
