# Generated by Django 3.2.5 on 2023-04-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0035_alter_vinculacion_datafono'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculacion',
            name='celular_confirma',
            field=models.CharField(default=1, max_length=12, verbose_name='Confirmación No. celular activado en DaviPlata'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vinculacion',
            name='celular',
            field=models.CharField(max_length=12, verbose_name='No. celular activado en DaviPlata'),
        ),
    ]
