# Generated by Django 3.2.5 on 2023-05-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0036_auto_20230502_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestores',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=15, null=True),
        ),
    ]
