# Generated by Django 3.2.5 on 2023-04-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0036_auto_20230403_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculacion',
            name='barrio',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vinculacion',
            name='localidad',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
