# Generated by Django 3.2.5 on 2023-04-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0037_auto_20230403_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculacion',
            name='contingencia',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default=1, max_length=2, verbose_name='¿Cliente contingencia?'),
            preserve_default=False,
        ),
    ]
