# Generated by Django 3.2.5 on 2023-04-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0038_vinculacion_contingencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculacion',
            name='etnico',
            field=models.CharField(choices=[('Ninguno', 'Ninguno'), ('Gitano o Rrom', 'Gitano o Rrom'), ('Palenquero', 'Palenquero'), ('Raizal', 'Raizal'), ('Negro(a), Mulato(a),afrodecendiente(a), afrocolombiano(a)', 'Negro(a), Mulato(a),afrodecendiente(a), afrocolombiano(a)'), ('Indigena', 'Indigena'), ('Prefiere no responder', 'Prefiere no responder')], default=1, max_length=70, verbose_name='El comercio se identifica con algún grupo etnico en particular?'),
            preserve_default=False,
        ),
    ]
