# Generated by Django 3.2.5 on 2023-04-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0039_vinculacion_etnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculacion',
            name='Proveedor',
            field=models.CharField(default='Firstsource', max_length=30),
        ),
    ]
