# Generated by Django 3.2.5 on 2023-04-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0040_vinculacion_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculacion',
            name='Proveedor',
            field=models.CharField(default='FirstSource', max_length=30),
        ),
    ]
