# Generated by Django 3.2.5 on 2023-05-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0040_alter_daviplata_rdab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daviplata',
            name='rdab',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='REFERENCIAS DETALLES ADICIONALES BASE'),
        ),
    ]
