# Generated by Django 3.2.5 on 2023-04-03 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0041_alter_vinculacion_proveedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vinculacion',
            old_name='Proveedor',
            new_name='proveedor',
        ),
    ]
