# Generated by Django 3.2.5 on 2023-04-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0042_rename_proveedor_vinculacion_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculacion',
            name='proveedor',
            field=models.CharField(blank=True, default='FirstSource', max_length=30, null=True),
        ),
    ]
