# Generated by Django 3.2.5 on 2023-05-04 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0042_auto_20230504_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daviplata',
            name='Sarlaft_activos',
            field=models.CharField(blank=True, choices=[('NO', 'NO'), ('SI', 'SI')], max_length=50, null=True, verbose_name='Sarlaft/Lavado de activos'),
        ),
        migrations.AlterField(
            model_name='daviplata',
            name='acude',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daviplata.acude', verbose_name='¿A quien acude?'),
        ),
        migrations.AlterField(
            model_name='daviplata',
            name='computador',
            field=models.CharField(blank=True, choices=[('NO', 'NO'), ('SI', 'SI')], max_length=50, null=True, verbose_name='Herramientas: Computador'),
        ),
        migrations.AlterField(
            model_name='daviplata',
            name='cual',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='especificado Grupo Etnico'),
        ),
        migrations.AlterField(
            model_name='daviplata',
            name='datafono',
            field=models.CharField(blank=True, choices=[('NO', 'NO'), ('SI', 'SI')], max_length=50, null=True, verbose_name='Herramientas: Datafono'),
        ),
        migrations.AlterField(
            model_name='daviplata',
            name='deposito_retiro',
            field=models.CharField(blank=True, choices=[('NO', 'NO'), ('SI', 'SI')], max_length=50, null=True, verbose_name='Depósito y Retiro DAVIVIENDA'),
        ),
        migrations.AlterField(
            model_name='daviplata',
            name='deposito_retiro_propio',
            field=models.CharField(blank=True, choices=[('NO', 'NO'), ('SI', 'SI')], max_length=50, null=True, verbose_name='Servicio: Depósito de retiro DaviPlata'),
        ),
        migrations.AlterField(
            model_name='daviplata',
            name='fecha_capacitacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de la última capacitación'),
        ),
        migrations.AlterField(
            model_name='daviplata',
            name='firma',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='daviplata',
            name='impresora',
            field=models.CharField(blank=True, choices=[('NO', 'NO'), ('SI', 'SI')], max_length=50, null=True, verbose_name='Herramientas: Impresora'),
        ),
        migrations.AlterField(
            model_name='daviplata',
            name='latitud',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='daviplata',
            name='lector',
            field=models.CharField(blank=True, choices=[('NO', 'NO'), ('SI', 'SI')], max_length=50, null=True, verbose_name='Herramientas: Lector de código de barras'),
        ),
        migrations.AlterField(
            model_name='daviplata',
            name='longitud',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='daviplata',
            name='medio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daviplata.medio'),
        ),
        migrations.AlterField(
            model_name='daviplata',
            name='medio_especificado',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Medio especificado'),
        ),
        migrations.AlterField(
            model_name='daviplata',
            name='ninguno_especificado',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='daviplata',
            name='pago_propios',
            field=models.CharField(blank=True, choices=[('NO', 'NO'), ('SI', 'SI')], max_length=50, null=True, verbose_name='Servicio: Pago de productos propios'),
        ),
        migrations.AlterField(
            model_name='daviplata',
            name='pago_subsidios',
            field=models.CharField(blank=True, choices=[('NO', 'NO'), ('SI', 'SI')], max_length=50, null=True, verbose_name='Pagos de Subsidios por Giro'),
        ),
        migrations.AlterField(
            model_name='daviplata',
            name='razon_no',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Razón indicada de no implementacion'),
        ),
        migrations.AlterField(
            model_name='daviplata',
            name='recaudo_servicios',
            field=models.CharField(blank=True, choices=[('NO', 'NO'), ('SI', 'SI')], max_length=50, null=True, verbose_name='Recaudo servicios públicos y privados'),
        ),
        migrations.AlterField(
            model_name='daviplata',
            name='sarlaft_informa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daviplata.acudeotro', verbose_name='SARLAFT. ¿A quien informaría?'),
        ),
        migrations.AlterField(
            model_name='daviplata',
            name='se_implementa',
            field=models.CharField(blank=True, choices=[('NO', 'NO'), ('SI', 'SI')], max_length=50, null=True, verbose_name='Se logro Implementar el Rompetráfico'),
        ),
        migrations.AlterField(
            model_name='daviplata',
            name='servicio_depositos',
            field=models.CharField(blank=True, choices=[('NO', 'NO'), ('SI', 'SI')], max_length=50, null=True, verbose_name='Servicio: Depósitos y retiros de cuentas ahorro y corriente'),
        ),
        migrations.AlterField(
            model_name='daviplata',
            name='servicio_pagos',
            field=models.CharField(blank=True, choices=[('NO', 'NO'), ('SI', 'SI')], max_length=50, null=True, verbose_name='Servicio: Pagos de subsidios por giros'),
        ),
        migrations.AlterField(
            model_name='daviplata',
            name='servicio_recaudo',
            field=models.CharField(blank=True, choices=[('NO', 'NO'), ('SI', 'SI')], max_length=50, null=True, verbose_name='Servicio: Recaudo servicios públicos y privados'),
        ),
        migrations.AlterField(
            model_name='daviplata',
            name='tip_riesgo',
            field=models.CharField(blank=True, choices=[('NO', 'NO'), ('SI', 'SI')], max_length=50, null=True, verbose_name='Tips de Riesgo'),
        ),
        migrations.AlterField(
            model_name='daviplata',
            name='tip_seguridad',
            field=models.CharField(blank=True, choices=[('NO', 'NO'), ('SI', 'SI')], max_length=50, null=True, verbose_name='Tips de Seguridad'),
        ),
        migrations.AlterField(
            model_name='daviplata',
            name='url_img_f',
            field=models.ImageField(blank=True, null=True, upload_to='IMG FACHADA', verbose_name='URL IMAGEN FACHADA'),
        ),
        migrations.AlterField(
            model_name='daviplata',
            name='url_img_m',
            field=models.ImageField(blank=True, null=True, upload_to='IMG MATERIAL', verbose_name='URL IMAGEN IMPL. MATERIAL'),
        ),
        migrations.AlterField(
            model_name='daviplata',
            name='visualizar',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
