# Generated by Django 3.2.5 on 2023-05-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0043_auto_20230504_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daviplata',
            name='transacciones',
            field=models.CharField(blank=True, choices=[('NO', 'NO'), ('SI', 'SI')], max_length=50, null=True, verbose_name='Conocimiento para realizar transacciones'),
        ),
    ]
