# Generated by Django 3.2.5 on 2023-04-04 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0043_alter_vinculacion_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vinculacion',
            name='tipo_id',
        ),
    ]
