# Generated by Django 3.2.5 on 2023-05-04 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0044_alter_daviplata_transacciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daviplata',
            name='fecha_encuesta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='daviplata',
            name='tipo_no_efectiva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daviplata.tiponoefectiva'),
        ),
        migrations.AlterField(
            model_name='daviplata',
            name='visita_efectiva',
            field=models.CharField(blank=True, choices=[('NO', 'NO'), ('SI', 'SI')], max_length=2, null=True),
        ),
    ]
