# Generated by Django 3.2.5 on 2023-05-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0048_alter_daviplata_obervacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daviplata',
            name='red',
            field=models.CharField(max_length=15),
        ),
    ]
