# Generated by Django 3.2.5 on 2023-05-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0049_alter_daviplata_red'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daviplata',
            name='red',
            field=models.CharField(choices=[('Puntored', 'Puntored'), ('Conred', 'Conred'), ('Punto de Pago ', 'Punto de Pago ')], max_length=15),
        ),
    ]
