# Generated by Django 3.2.5 on 2023-05-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0050_alter_daviplata_red'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculacion',
            name='registro_daviplata',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO'), ('Ya esta activo', 'Ya esta activo')], max_length=20, null=True, verbose_name='¿Se realizó registro en DaviPlata?'),
        ),
    ]
