# Generated by Django 3.2.5 on 2023-04-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0050_alter_vinculacion_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculacion',
            name='celular_confirma',
            field=models.CharField(max_length=12, unique=True, verbose_name='Confirmación No. celular activado en DaviPlata'),
        ),
    ]
