# Generated by Django 3.2.5 on 2023-05-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0051_alter_vinculacion_registro_daviplata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculacion',
            name='se_registro',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO'), ('Ya esta activo', 'Ya está activo')], max_length=20, null=True, verbose_name='¿Se realizó registro en perfil mi negocio?'),
        ),
        migrations.AlterField(
            model_name='vinculacion',
            name='solicito_tencard',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO'), ('Ya tiene la tencard', 'Ya tiene la tencard')], max_length=40, null=True, verbose_name='¿Se solicitó la tentcard?'),
        ),
        migrations.AlterField(
            model_name='vinculacion',
            name='sticker',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='Se pego Sticker'),
        ),
    ]
