# Generated by Django 3.2.5 on 2023-04-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0051_alter_vinculacion_celular_confirma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculacion',
            name='porque_no_solicito',
            field=models.CharField(choices=[('Cliente ya tiene la tencard', 'Cliente ya tiene la tencard'), ('Fallas en la app', 'Fallas en la app'), ('No permitió el registro en el prefil negocio', 'No permitió el registro en el prefil negocio'), ('Cliente no está interesado', 'Cliente no está interesado'), ('Solo activo daviplata para subsidios del gobierno', 'Solo activo daviplata para subsidios del gobierno'), ('Modo contingencia', 'Modo contingencia')], max_length=60, verbose_name='¿Por qué no se solicitó la tentcard?'),
        ),
        migrations.AlterField(
            model_name='vinculacion',
            name='razon_no_flanger',
            field=models.CharField(choices=[('Cliente ya tiene la tencard', 'Cliente ya tiene la tencard'), ('Fallas en la app', 'Fallas en la app'), ('No permitió el registro en el prefil negocio', 'No permitió el registro en el prefil negocio'), ('Cliente no está interesado', 'Cliente no está interesado'), ('Solo activo daviplata para subsidios del gobierno', 'Solo activo daviplata para subsidios del gobierno'), ('Modo contingencia', 'Modo contingencia')], max_length=60, verbose_name='Razón por la cual no se instaló el flanger'),
        ),
        migrations.AlterField(
            model_name='vinculacion',
            name='razon_no_sticker',
            field=models.CharField(choices=[('Cliente ya tiene la tencard', 'Cliente ya tiene la tencard'), ('Fallas en la app', 'Fallas en la app'), ('No permitió el registro en el prefil negocio', 'No permitió el registro en el prefil negocio'), ('Cliente no está interesado', 'Cliente no está interesado'), ('Solo activo daviplata para subsidios del gobierno', 'Solo activo daviplata para subsidios del gobierno'), ('Modo contingencia', 'Modo contingencia')], max_length=60, verbose_name='Razón por la cual no se pegó el sticker'),
        ),
    ]
