# Generated by Django 3.2.5 on 2023-05-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0052_auto_20230505_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daviplata',
            name='red',
            field=models.CharField(choices=[('PuntoRed (ConexRed)', 'PuntoRed (ConexRed'), ('Conred', 'Conred'), ('Punto de Pago ', 'Punto de Pago ')], max_length=25),
        ),
    ]
