# Generated by Django 3.2.5 on 2023-04-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0052_auto_20230404_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculacion',
            name='flanger',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='No', max_length=2, null=True, verbose_name='Se instaló Flanger'),
        ),
        migrations.AlterField(
            model_name='vinculacion',
            name='razon_no_flanger',
            field=models.CharField(default='No hay stock', max_length=60, verbose_name='Razón por la cual no se instaló el flanger'),
        ),
    ]
