# Generated by Django 3.2.5 on 2023-05-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0053_alter_daviplata_red'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daviplata',
            name='otro_d_e',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Otro tipo de establecimiento'),
        ),
    ]
