# Generated by Django 3.2.5 on 2023-04-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0055_auto_20230404_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculacion',
            name='tipo_activacion',
            field=models.CharField(default='Presencial', max_length=30, verbose_name='Tipo activación'),
        ),
    ]
