# Generated by Django 3.2.5 on 2023-05-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0055_auto_20230505_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daviplata',
            name='t_senalizacion',
            field=models.CharField(blank=True, choices=[('Otro)', 'Otro'), ('Rompetrafico', 'Rompetrafico'), ('Aviso ', 'Aviso')], max_length=30, null=True, verbose_name='Tipo de señalizacion'),
        ),
    ]
