# Generated by Django 3.2.5 on 2023-04-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0056_alter_vinculacion_tipo_activacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculacion',
            name='tipo_activacion',
            field=models.CharField(blank=True, default='Presencial', max_length=30, null=True, verbose_name='Tipo activación'),
        ),
    ]
