# Generated by Django 3.2.5 on 2023-05-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0056_alter_daviplata_t_senalizacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoSenalizacion',
        ),
        migrations.AlterField(
            model_name='daviplata',
            name='otro_senalizacion',
            field=models.CharField(blank=True, choices=[('Flanger', 'Flanger'), ('Hablador', 'Hablador'), ('Peldaño', 'Peldaño'), ('Pendon', 'Pendon')], max_length=30, null=True, verbose_name='Otro especificado'),
        ),
        migrations.AlterField(
            model_name='daviplata',
            name='t_senalizacion',
            field=models.CharField(blank=True, choices=[('Otro', 'Otro'), ('Rompetrafico', 'Rompetrafico'), ('Aviso ', 'Aviso')], max_length=30, null=True, verbose_name='Tipo de señalizacion'),
        ),
    ]
