# Generated by Django 3.2.5 on 2023-04-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0057_alter_vinculacion_tipo_activacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculacion',
            name='razon_no_flanger',
            field=models.CharField(blank=True, default='No hay stock', max_length=60, null=True, verbose_name='Razón por la cual no se instaló el flanger'),
        ),
    ]
