# Generated by Django 3.2.5 on 2023-04-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0058_alter_vinculacion_razon_no_flanger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculacion',
            name='flanger',
            field=models.CharField(blank=True, default='No', max_length=2, null=True, verbose_name='Se instaló Flanger'),
        ),
    ]
