# Generated by Django 3.2.5 on 2023-04-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0059_alter_vinculacion_flanger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculacion',
            name='se_registro',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO'), ('Ya está activo', 'Ya está activo'), ('Modo contingencia', 'Modo contingencia')], max_length=20, verbose_name='¿Se realizó registro en perfil mi negocio?'),
        ),
    ]
