# Generated by Django 3.2.5 on 2023-05-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0059_auto_20230508_1457'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medio',
        ),
        migrations.AlterField(
            model_name='daviplata',
            name='sarlaft_informa',
            field=models.CharField(blank=True, choices=[('Servicio al Cliente', 'Servicio al Cliente'), ('Operador', 'Operador'), ('puntored ', 'puntored'), ('Chat Plataforma', 'Chat Plataforma'), ('Asesor Comercial ', 'Asesor Comercial'), ('Conred ', 'Conred'), ('No sabe', 'No sabe'), ('Supervisor', 'Supervisor'), ('Punto de Pago', 'Punto de Pago')], max_length=30, null=True, verbose_name='SARLAFT. ¿A quien informaría?'),
        ),
    ]
