# Generated by Django 3.2.5 on 2023-05-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0060_auto_20230508_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daviplata',
            name='red',
            field=models.CharField(choices=[('PuntoRed (ConexRed)', 'PuntoRed (ConexRed)'), ('Conred', 'Conred'), ('Punto de Pago ', 'Punto de Pago'), ('PuntoRed (ConexRed) Onboarding', 'PuntoRed (ConexRed) Onboarding')], max_length=60),
        ),
    ]
