# Generated by Django 3.2.5 on 2023-04-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0060_alter_vinculacion_se_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculacion',
            name='no_registro',
            field=models.CharField(choices=[('Cliente ya estaba registrado', 'Cliente ya estaba registrado'), ('Cliente no está interesado', 'Cliente no está interesado'), ('Cliente mejor de edad', 'Cliente mejor de edad'), ('Fallas en la app', 'Fallas en la app'), ('Cliente activo en Sim', 'Cliente activo en Sim'), ('Sistema operativo no permite registro', 'Sistema operativo no permite registro'), ('Cliente desconfia', 'Cliente desconfia'), ('Cliente no tiene tiempo', 'Modo contingencia')], max_length=37, verbose_name='¿Por qué no se realizó el registro en perfil mi negocio?'),
        ),
    ]
