# Generated by Django 3.2.5 on 2023-05-09 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0061_alter_daviplata_red'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daviplata',
            name='latitud',
            field=models.CharField(blank=True, default='error', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='daviplata',
            name='longitud',
            field=models.CharField(blank=True, default='error', max_length=15, null=True),
        ),
    ]
