# Generated by Django 3.2.5 on 2023-04-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0061_alter_vinculacion_no_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculacion',
            name='registro_daviplata',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO'), ('Ya esta activo', 'Ya esta activo'), ('Modo Contingencia', 'Modo Contingencia')], max_length=20, verbose_name='¿Se realizó registro en DaviPlata?'),
        ),
    ]
