# Generated by Django 3.2.5 on 2023-04-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0062_alter_vinculacion_registro_daviplata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculacion',
            name='razon_no_sticker',
            field=models.CharField(choices=[('No está autorizado por el dueño', 'No está autorizado por el dueño'), ('No está interesado', 'No está interesado'), ('No se pudo registrar', 'No se pudo registrar'), ('Vendedor informal', 'Vendedor informal'), ('No hay espacio en el comercio', 'No hay espacio en el comercio'), ('No hay Stock', 'No hay Stock'), ('Se instaló flanger', 'Se instaló flanger')], max_length=60, verbose_name='Razón por la cual no se pegó el sticker'),
        ),
    ]
