# Generated by Django 3.2.5 on 2023-05-09 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0062_auto_20230508_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daviplata',
            name='latitud',
            field=models.CharField(blank=True, default='error', max_length=100, null=True),
        ),
    ]
