# Generated by Django 3.2.5 on 2023-05-09 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0064_alter_daviplata_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daviplata',
            name='latitud',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='daviplata',
            name='longitud',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='vinculacion',
            name='latitud',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vinculacion',
            name='longitud',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
