# Generated by Django 3.2.5 on 2023-05-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0065_auto_20230508_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculacion',
            name='latitud',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vinculacion',
            name='longitud',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
