# Generated by Django 3.2.5 on 2023-05-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0066_auto_20230509_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daviplata',
            name='numero_movil',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
