# Generated by Django 3.2.5 on 2023-05-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0067_alter_daviplata_numero_movil'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculacion',
            name='hora',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
    ]
