# Generated by Django 3.2.5 on 2023-04-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0067_auto_20230405_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculacion',
            name='solicito_tencard',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO'), ('Ya tiene la tencard', 'Ya tiene la tencard'), ('Modo Contingencia', 'Modo Contingencia')], max_length=40, verbose_name='¿Se solicitó la tentcard?'),
        ),
    ]
