# Generated by Django 3.2.5 on 2023-04-10 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0068_alter_vinculacion_solicito_tencard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculacion',
            name='motivo_no_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daviplata.motivonoregistro', verbose_name='¿Por qué no se realizó el registro DaviPlata?'),
        ),
    ]
