# Generated by Django 3.2.5 on 2023-05-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0068_vinculacion_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vinculacion',
            name='hora',
        ),
        migrations.AddField(
            model_name='daviplata',
            name='hora',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
    ]
