# Generated by Django 3.2.5 on 2023-04-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0069_alter_vinculacion_motivo_no_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculacion',
            name='no_registro',
            field=models.CharField(choices=[('Cliente ya estaba registrado', 'Cliente ya estaba registrado'), ('Fallas en la app', 'Fallas en la app'), ('Cliente no está interesado', 'Cliente no está interesado'), ('Cliente tercera edad', 'Cliente tercera edad'), ('Sistema operativo no permite registro', 'Sistema operativo no permite registro'), ('Cliente desconfia', 'Cliente desconfia'), ('Cliente no tiene tiempo', 'Cliente no tiene tiempo'), ('Cliente no tiene documentos en el momento', 'Cliente no tiene documentos en el momento'), ('Modo contingencia', 'Modo contingencia')], max_length=42, verbose_name='¿Por qué no se realizó el registro en perfil mi negocio?'),
        ),
    ]
