# Generated by Django 3.2.5 on 2023-04-10 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0070_alter_vinculacion_no_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vinculacion',
            name='no_registro',
        ),
    ]
