# Generated by Django 3.2.5 on 2023-05-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0071_alter_daviplata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daviplata',
            name='url_img_f',
            field=models.ImageField(null=True, upload_to='IMG FACHADA', verbose_name='URL IMAGEN FACHADA'),
        ),
    ]
