# Generated by Django 3.2.5 on 2023-04-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0072_alter_vinculacion_porque_no_solicito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculacion',
            name='contingencia',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='¿Cliente contingencia?'),
        ),
    ]
