# Generated by Django 3.2.5 on 2023-05-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0074_alter_daviplata_pdv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daviplata',
            name='pdv',
            field=models.CharField(blank=True, choices=[('NO', 'NO'), ('SI', 'SI')], max_length=50, null=True, verbose_name='¿PDV permite realizar la visita?'),
        ),
    ]
