# Generated by Django 3.2.5 on 2023-05-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0076_auto_20230518_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daviplata',
            name='t_senalizacion',
            field=models.CharField(choices=[('Otro', 'Otro'), ('Rompetrafico', 'Rompetrafico'), ('Aviso ', 'Aviso')], max_length=30, null=True, verbose_name='Tipo de señalizacion'),
        ),
    ]
