# Generated by Django 3.2.5 on 2023-05-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0077_alter_daviplata_t_senalizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daviplata',
            name='se_implementa',
            field=models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=50, null=True, verbose_name='Se logro Implementar el Rompetráfico'),
        ),
    ]
