# Generated by Django 3.2.5 on 2023-05-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0078_alter_daviplata_se_implementa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daviplata',
            name='coincide_direccion',
            field=models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=2, null=True),
        ),
    ]
