# Generated by Django 3.2.5 on 2023-05-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0080_alter_daviplata_nombre_coincide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculacion',
            name='porque_no_solicito',
            field=models.CharField(blank=True, choices=[('Clinete ya tiene la tencard', 'Clinete ya tiene la tencard'), ('Fallas en la app', 'Fallas en la app'), ('No permitió el registro en el perfil mi negocio', 'No permitió el registro en el perfil mi negocio'), ('Cliente no esta interesado', 'Cliente no esta interesado'), ('Solo activo Daviplata para subsidios del gobierno', 'Solo activo Daviplata para subsidios del gobierno'), ('Modo contigencia', 'Modo contigencia')], max_length=80, null=True, verbose_name='¿Por qué no se solicitó la tentcard?'),
        ),
    ]
