# Generated by Django 3.2.5 on 2023-05-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0081_alter_vinculacion_porque_no_solicito'),
    ]

    operations = [
        migrations.AddField(
            model_name='daviplata',
            name='minuto',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
    ]
