# Generated by Django 3.2.5 on 2023-05-29 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0083_auto_20230529_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daviplata',
            old_name='continecia',
            new_name='contingencia_img',
        ),
    ]
