# Generated by Django 3.2.5 on 2023-05-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0084_rename_continecia_daviplata_contingencia_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daviplata',
            name='contingencia_img',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
