# Generated by Django 3.2.5 on 2023-05-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0085_alter_daviplata_contingencia_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daviplata',
            name='contingencia_img',
        ),
        migrations.AddField(
            model_name='daviplata',
            name='contingencia_img1',
            field=models.BooleanField(default=False),
        ),
    ]
