# Generated by Django 3.2.5 on 2023-06-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0088_auto_20230601_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculacion',
            name='num_dir1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vinculacion',
            name='num_dir2',
            field=models.IntegerField(null=True),
        ),
    ]
