# Generated by Django 3.2.5 on 2023-06-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0090_alter_vinculacion_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculacion',
            name='num_dir1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vinculacion',
            name='num_dir2',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
