# Generated by Django 3.2.5 on 2023-06-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0091_auto_20230601_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculacion',
            name='detail_complemento',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
