# Generated by Django 3.2.5 on 2023-06-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0092_vinculacion_detail_complemento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculacion',
            name='detail_complemento',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
