# Generated by Django 3.2.5 on 2023-06-06 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0094_alter_daviplata_tipo_no_efectiva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculacion',
            name='dir_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daviplata.direccion'),
        ),
    ]
