# Generated by Django 3.2.5 on 2023-06-06 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0095_alter_vinculacion_dir_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculacion',
            name='dir_a',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='daviplata.direccion'),
        ),
    ]
