# Generated by Django 3.2.5 on 2023-06-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0096_alter_vinculacion_dir_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daviplata',
            name='hora',
            field=models.CharField(blank=True, default=0, max_length=30, null=True),
        ),
    ]
