# Generated by Django 3.2.5 on 2023-06-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0097_alter_daviplata_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculacion',
            name='novedad',
            field=models.BooleanField(default=False),
        ),
    ]
