# Generated by Django 3.2.5 on 2023-06-08 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0098_alter_vinculacion_novedad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vinculacion',
            name='novedad',
        ),
    ]
