# Generated by Django 3.2.5 on 2023-06-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0099_remove_vinculacion_novedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculacion',
            name='cambio',
            field=models.BooleanField(default=False),
        ),
    ]
