# Generated by Django 3.2.5 on 2023-06-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0100_vinculacion_cambio'),
    ]

    operations = [
        migrations.AddField(
            model_name='daviplata',
            name='fecha_eliminar',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
