# Generated by Django 3.2.5 on 2023-06-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0101_daviplata_fecha_eliminar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daviplata',
            name='fecha_eliminar',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
