# Generated by Django 3.2.5 on 2023-06-14 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('daviplata', '0103_remove_daviplata_fecha_eliminar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculacion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_vinculacion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
