# Generated by Django 3.2.5 on 2023-06-15 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0105_alter_vinculacion_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculacion',
            name='tipo_gestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='tipo_gestion_vinculacion', to='daviplata.tipogestion'),
        ),
    ]
