# Generated by Django 3.2.5 on 2023-06-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0107_alter_daviplata_t_senalizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daviplata',
            name='t_senalizacion',
            field=models.CharField(choices=[('Otro', 'Otro'), ('Rompetrafico', 'Rompetrafico'), ('Aviso ', 'Aviso')], max_length=30, null=True, verbose_name='Tipo de señalizacion'),
        ),
    ]
