# Generated by Django 3.2.5 on 2023-06-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0109_alter_daviplata_t_senalizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daviplata',
            name='obervacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
