# Generated by Django 3.2.5 on 2023-06-27 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0111_asistencia_vinculacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia_vinculacion',
            name='id_gestor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='daviplata.gestores'),
        ),
    ]
