# Generated by Django 3.2.5 on 2023-06-27 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0112_asistencia_vinculacion_id_gestor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia_vinculacion',
            name='id_gestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daviplata.gestores'),
        ),
    ]
