# Generated by Django 3.2.5 on 2023-06-27 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('daviplata', '0113_alter_asistencia_vinculacion_id_gestor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia_vinculacion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
