# Generated by Django 3.2.5 on 2023-06-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0114_alter_asistencia_vinculacion_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia_vinculacion',
            name='check',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
