# Generated by Django 3.2.5 on 2023-06-28 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daviplata', '0117_alter_gestores_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asistencia_vinculacion',
        ),
    ]
