# Generated by Django 3.2.5 on 2022-09-12 13:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolsa',
            fields=[
                ('bolsa', models.CharField(max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('codigo', models.CharField(blank=True, max_length=28, null=True)),
                ('fecha_bolsa', models.DateTimeField(auto_now_add=True, null=True)),
                ('cantidad_vi', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad visitas')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalFisico',
            fields=[
                ('bolsa_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='fisico.bolsa')),
                ('fecha', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha fisico')),
                ('estado', models.BooleanField(default=True)),
                ('bolsa', models.CharField(db_index=True, max_length=11, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('codigo', models.CharField(blank=True, max_length=28, null=True)),
                ('fecha_bolsa', models.DateTimeField(blank=True, editable=False, null=True)),
                ('cantidad_vi', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad visitas')),
                ('id_guia', models.IntegerField(blank=True, db_index=True)),
                ('direccion', models.CharField(blank=True, max_length=240, null=True)),
                ('cantidad', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Cantidad Total')),
                ('destinatario', models.CharField(blank=True, max_length=100, null=True)),
                ('d_i', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_recepcion', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha gestion')),
                ('fecha_planilla', models.DateTimeField(blank=True, null=True)),
                ('est_planilla', models.CharField(blank=True, max_length=30, null=True)),
                ('id_planilla', models.IntegerField(blank=True, null=True)),
                ('fecha_descargue', models.DateField(blank=True, null=True, verbose_name='Descargue')),
                ('origen', models.CharField(blank=True, max_length=60, null=True)),
                ('destino', models.CharField(blank=True, max_length=60, null=True)),
                ('estado_destino', models.BooleanField(default=False)),
                ('fecha_visita', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical fisico',
                'verbose_name_plural': 'historical fisicos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'inconsistencias',
                'verbose_name_plural': 'inconsistencias',
            },
        ),
        migrations.CreateModel(
            name='Motivo_mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cobertura',
            fields=[
                ('bolsa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cobertura_bolsa', serialize=False, to='fisico.bolsa')),
                ('fecha', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha fisico')),
                ('pdf_cobertura', models.FileField(blank=True, null=True, upload_to='pdf_cobertura')),
                ('estado_mesa', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Fisico',
            fields=[
                ('bolsa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='fisico.bolsa')),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha fisico')),
                ('estado', models.BooleanField(default=True)),
                ('id_guia', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(blank=True, max_length=240, null=True)),
                ('cantidad', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Cantidad Total')),
                ('destinatario', models.CharField(blank=True, max_length=100, null=True)),
                ('d_i', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_recepcion', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha gestion')),
                ('fecha_planilla', models.DateTimeField(blank=True, null=True)),
                ('est_planilla', models.CharField(blank=True, max_length=30, null=True)),
                ('id_planilla', models.IntegerField(blank=True, null=True)),
                ('fecha_descargue', models.DateField(blank=True, null=True, verbose_name='Descargue')),
                ('origen', models.CharField(blank=True, max_length=60, null=True)),
                ('destino', models.CharField(blank=True, max_length=60, null=True)),
                ('estado_destino', models.BooleanField(default=False)),
                ('fecha_visita', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('fisico.bolsa', models.Model),
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('fecha', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha fisico')),
                ('estado', models.BooleanField(default=True)),
                ('seudo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='bd_paquete', serialize=False, to='base_cliente.bd_clie')),
                ('bolsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolsapaquete', to='fisico.bolsa')),
            ],
        ),
    ]
