# Generated by Django 3.2.5 on 2022-09-26 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fisico', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechaUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fisico.fisico')),
            ],
        ),
    ]
