# Generated by Django 3.2.5 on 2022-09-26 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fisico', '0004_auto_20220926_1227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FechaUpdate',
        ),
    ]
