# Generated by Django 3.2.5 on 2023-03-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisico', '0004_auto_20230308_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='fisico',
            name='seudo_track',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalfisico',
            name='seudo_track',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
