# Generated by Django 3.2.5 on 2022-09-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisico', '0005_delete_fechaupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisico',
            name='fecha_recepcion',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha gestion'),
        ),
        migrations.AlterField(
            model_name='historicalfisico',
            name='fecha_recepcion',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha gestion'),
        ),
    ]
