# Generated by Django 3.2.5 on 2022-10-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisico', '0007_auto_20221021_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bolsa',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='bolsa',
            name='fecha',
        ),
        migrations.AddField(
            model_name='fisico',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fisico',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha fisico'),
        ),
    ]
