# Generated by Django 3.2.5 on 2022-10-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisico', '0008_auto_20221021_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fisico',
            name='fecha_visita',
        ),
        migrations.AddField(
            model_name='bolsa',
            name='fecha_visita',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
