# Generated by Django 3.2.5 on 2022-11-04 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('argumento', '0001_initial'),
        ('fisico', '0010_auto_20221021_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fisico',
            name='cod_ins',
        ),
        migrations.AddField(
            model_name='bolsa',
            name='cod_ins',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='argumento.est_clie'),
        ),
    ]
