# Generated by Django 3.2.5 on 2022-11-11 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('users', '0002_user_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente'),
        ),
    ]
