# Generated by Django 3.2.5 on 2022-12-29 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_logsesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='logsesion',
            name='log',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logsesion',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
