# Generated by Django 3.2.5 on 2022-12-29 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20221229_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsesion',
            name='cliente',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='logsesion',
            name='documento',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='logsesion',
            name='log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='logsesion',
            name='usuario',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
