# Generated by Django 3.2.5 on 2022-12-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20221229_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsesion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
