# Generated by Django 3.2.5 on 2023-03-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_logsesion_accion'),
    ]

    operations = [
        migrations.AddField(
            model_name='logsesion',
            name='action_flag',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='action flag'),
            preserve_default=False,
        ),
    ]
