# Generated by Django 3.2.5 on 2023-03-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_logsesion_action_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsesion',
            name='action_flag',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='action flag'),
        ),
    ]
