# Generated by Django 3.2.5 on 2023-03-28 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_logsesion_action_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logsesion',
            name='action_flag',
        ),
    ]
