# Generated by Django 3.2.5 on 2023-04-19 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_alter_cliente_rol'),
        ('users', '0012_remove_logsesion_action_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente', verbose_name='Permisos cliente'),
        ),
    ]
