# Generated by Django 3.2.5 on 2023-04-25 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_alter_cliente_rol'),
        ('users', '0019_alter_user_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalUser',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, max_length=20, verbose_name='Usuario')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nombres', models.CharField(blank=True, max_length=30)),
                ('apellidos', models.CharField(blank=True, max_length=30)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otros')], max_length=1)),
                ('ocupation', models.CharField(blank=True, choices=[('0', 'Custodia'), ('1', 'Mesa'), ('2', 'Call'), ('3', 'Courrier'), ('4', 'Sig'), ('5', 'Tecnologia'), ('6', 'Administrador'), ('7', 'Cliente')], max_length=1, null=True, verbose_name='Ocupacion')),
                ('d_i', models.CharField(max_length=12, verbose_name='Documento de identidad')),
                ('roles', models.IntegerField(blank=True, choices=[(1, 'Consulta'), (2, 'Davivienda Administrador'), (3, 'Daviplata'), (4, 'Custodia'), (5, 'Courrier'), (6, 'Mesa de control'), (7, 'Sig'), (8, 'call center')], null=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('ciudad', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cliente.ciudad')),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cliente.cliente', verbose_name='Cliente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Permisos de usuarios',
                'verbose_name_plural': 'historical Permisos de usuario',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
