# Generated by Django 3.2.5 on 2023-04-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20230426_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='tipo_d_i',
            field=models.CharField(blank=True, choices=[(1, 'CC')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo_d_i',
            field=models.CharField(blank=True, choices=[(1, 'CC')], max_length=2, null=True),
        ),
    ]
