# Generated by Django 3.2.5 on 2023-05-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20230426_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='tipo_d_i',
            field=models.CharField(blank=True, choices=[('CC', 'CC')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo_d_i',
            field=models.CharField(blank=True, choices=[('CC', 'CC')], max_length=2, null=True),
        ),
    ]
