# Generated by Django 3.2.5 on 2023-05-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20230502_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='tipo_d_i',
            field=models.CharField(blank=True, choices=[('Cedula', 'Cedula')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo_d_i',
            field=models.CharField(blank=True, choices=[('Cedula', 'Cedula')], max_length=10, null=True),
        ),
    ]
