# Generated by Django 3.2.5 on 2023-05-31 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_asistencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistencia',
            old_name='User',
            new_name='user',
        ),
    ]
