# Generated by Django 3.2.5 on 2023-05-31 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_rename_user_asistencia_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
