# Generated by Django 3.2.5 on 2023-05-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_asistencia_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
