# Generated by Django 3.2.5 on 2023-06-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_asistencia_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='rol_m',
            field=models.ManyToManyField(blank=True, null=True, to='users.Modulos'),
        ),
    ]
