# Generated by Django 3.2.5 on 2023-06-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20230602_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol_m',
            field=models.ManyToManyField(blank=True, to='users.Modulos'),
        ),
    ]
