# Generated by Django 3.2.5 on 2023-06-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_user_rol_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='ocupation',
            field=models.CharField(blank=True, choices=[('0', 'Custodia'), ('1', 'Mesa'), ('2', 'Call'), ('3', 'Courrier'), ('4', 'Sig'), ('5', 'Tecnologia'), ('6', 'Administrador'), ('7', 'Cliente'), ('8', 'COOR_RETAIL')], max_length=1, null=True, verbose_name='Ocupacion'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ocupation',
            field=models.CharField(blank=True, choices=[('0', 'Custodia'), ('1', 'Mesa'), ('2', 'Call'), ('3', 'Courrier'), ('4', 'Sig'), ('5', 'Tecnologia'), ('6', 'Administrador'), ('7', 'Cliente'), ('8', 'COOR_RETAIL')], max_length=1, null=True, verbose_name='Ocupacion'),
        ),
    ]
